name: Manual N2YO Satellite Report

on:
  workflow_dispatch:  # Manual trigger

jobs:
  run-n2yo-fetcher:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug Secrets (Sanitized)
        run: |
          echo "Checking required secrets..."
          [[ -z "${{ secrets.N2YO_API_KEY }}" ]] && echo "Missing N2YO_API_KEY" || echo "N2YO_API_KEY is set"
          [[ -z "${{ secrets.SMTP_SERVER }}" ]] && echo "Missing SMTP_SERVER" || echo "SMTP_SERVER is set"
          [[ -z "${{ secrets.RECEIVER_EMAIL }}" ]] && echo "Missing RECEIVER_EMAIL" || echo "RECEIVER_EMAIL is set"

      - name: Run N2YO Fetcher Script
        env:
          N2YO_API_KEY: ${{ secrets.N2YO_API_KEY }}
          OBSERVER_LAT: ${{ secrets.OBSERVER_LAT }}
          OBSERVER_LNG: ${{ secrets.OBSERVER_LNG }}
          OBSERVER_ALT: ${{ secrets.OBSERVER_ALT }}
          CATEGORY_ID: ${{ secrets.CATEGORY_ID }}
          SEARCH_RADIUS_DEGREES: ${{ secrets.SEARCH_RADIUS_DEGREES }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python app.py
